// Generated by https://quicktype.io

export interface CheckTokenResponse {
  token: string;
  user:  User;
}

export interface User {
  _id:        string;
  name:       string;
  email:      string;
  password:   string;
  confirmado: boolean;
  isActive:   boolean;
  presupuesto: number;
  __v:        number;
}
