// Generated by https://quicktype.io

export interface GetGastoResponse {
  _id:       string;
  cantidad:  number;
  categoria: string;
  nombre:    string;
  usuario:   string;
  createdAt: string;
  __v:       number;
}
